services:
  db:
    image: mysql:9.1.0
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3306:3306

  wordpress:
    depends_on:
      - db
    build:
      context: .
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: wordpress
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
