# Instalação completa do WordPress e suas dependências
# WordPress, com PHP, MySQL e Apache
services:
  db:
    image: mysql:9.0.1
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    ports:
      - "3306:3306"

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5.2.1
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: wordpress
    restart: always
    ports:
      - "8080:80"

  wordpress:
    depends_on:
      - db
    image: wordpress:6.6.1-php8.3-apache
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
