# A Aplicação ira rodar em http://localhost:8080/
# E todos os arquivos da aplicação devem ser postos na pasta app
services:
  web:
    image: php:8.1-apache
    container_name: php_app
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
